### ISSUE TITLE
Doesn't work on Debian 12 new install

### ISSUE THREAD

**Issue by codemorix0** [flathub/io.github.Foldex.AdwSteamGtk#56]
When i run it with: flatpak run io.github.Foldex.AdwSteamGtk
I get this message in terminal:

Traceback (most recent call last):
  File "/app/share/adwaita-steam-gtk/adwaita_steam_gtk/window.py", line 225, in install_theme
    (ret, msg) = install.run(options, self.beta_support)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/share/adwaita-steam-gtk/adwaita_steam_gtk/install.py", line 184, in run
    cmd = gen_cmd_line(options, beta_support)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/share/adwaita-steam-gtk/adwaita_steam_gtk/install.py", line 68, in gen_cmd_line
    button_layout = get_button_layout()
                    ^^^^^^^^^^^^^^^^^^^
  File "/app/share/adwaita-steam-gtk/adwaita_steam_gtk/install.py", line 160, in get_button_layout
    button_layout = portal.call_sync('org.freedesktop.portal.Settings.ReadOne', args, Gio.DBusCallFlags.NONE, -1, None)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gi.repository.GLib.GError: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Não existe o método “ReadOne” (19)

When i try with sudo -i flatpak run io.github.Foldex.AdwSteamGtk
I don't get a terminal message, but i get an error that says:
Installation: Failed to find symbolic link ~/.steam .........

I have steam flatpak installed, and recently did a fresh install of debian 12. (I got it working in previous install, about 2 weeks ago)

**Comment by Foldex** [comment]
Please use the correct issue tracker for this.
https://github.com/Foldex/AdwSteamGtk/issues
